### ISSUE TITLE
Will not download contacts from Nextcloud 14.0.3

### ISSUE THREAD

**Issue by Garfonso** [BlackSenator/carddav2fb_XR#10]
I have a nextcloud server running and was importing contacts using the old carddav2fb. But that failed for image import and produced a lot of warnings... but it basically still works.

Today I tried to switch to this "extended" version, but it refuses to download any contacts form my nextcloud server. Log output:
`php carddav2fb.php download -vvv
Downloading vCard(s) from account FritzBox
    0 [>---------------------------] < 1 sec 2.0 MiB
Downloaded 0 vCard(s)
Parsing vCard(s)`

I dug a bit in the code (because logging is not very verbose), added some more debug output (or uncommented it) and the request the tool sends seems to be to few carddav like so the server responds with a HTML version of the contact list. And of course all the HTML gets filtered away and no contact stays... 

I looked a bit at the request, that is send to the server and am a bit puzzled that any server responds to this request with a xml list of contacts at all... it contains no carddav request at all... huh? Not even content type definition.

Anyway, I read somewhere that some people had it running with nextcloud. I'm not sure why that is and where the differences might be. Also it would be helpful to add a bit more debug output (especially with -vvv) than there currently is...

Some information about my System:
Ubuntu 18.04.1 Server, nextcloud runs localy on the same server (but I use the full URL to access it anyways, because SSL is enforced).
Nexclout version 14.0.3 (current stable, was 13.0.4 before, I updated just for this tool, but made no difference)
php version is 7.2.10.

I can create you a test account for my server, if that helps.

**Comment by Garfonso** [comment]
Update: I checked which "old" version I am using. It seems I use https://github.com/jens-maus/carddav2fb which has a very different CardDav backend then what you are using, right?
It creates a proper VCard request to the server ( https://github.com/jens-maus/carddav2fb/blob/master/lib/CardDAV-PHP/carddav.php#L331 ) which I am completely missing in this version of the tool... 

Maybe it would be possible to switch the backend?

**Comment by BlackSenator** [comment]
Solution moved to https://github.com/BlackSenator/carddav2fb
