### ISSUE TITLE
gelöst: diverse Warnungen, Fehlermeldungen mit anschließendem Abbruch beim Ablauf unter PHP 7.1

### ISSUE THREAD

**Issue by axelrathey** [BlackSenator/carddav2fb_XR#5]
Hallo BlackSenator,

taste mich gerade heran an die Installation. Zunächst mal installiert "git clone" das Script aufgrund des angehängten "_XR" in ein anderes Verzeichnis, so dass auch das cd Kommando angepasst werden muss.

Bitte ändern von bisher: 

cd /
git clone https://github.com/BlackSenator/carddav2fb_XR.git
cd carddav2fb

in nun (3. Zeile):

cd /
git clone https://github.com/BlackSenator/carddav2fb_XR.git
cd carddav2fb_XR

Danke, melde mich, wie ich damit weiter komme.

Gruß
Axel

**Comment by axelrathey** [comment]
Hallo BlackSenator,

habe die Installation so weit durchgeführt allerdings habe ich hier PHP7.1 und die Pfade dahingehend soweit ersichtlich angepasst. Die Installation des Composers und der dbase extension liegt auch soweit durch.

Beim Ausführen des Scriptes mit

"php carddav2fb_XR run"

kommen nun aber die folgende Fehlermeldungen mit anschließendem Abbruch, die -vvv option bringt dabei nicht viel mehr:

PHP Warning:  Illegal string offset 'user' in /root/carddav2fb_XR/src/RunCommand.php on line 37
Downloading vCard(s) from account h
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Andig\backendProvider() must be of the type array, string given, called in /root/carddav2fb_XR/src/RunCommand.php on line 38 and defined in /root/carddav2fb_XR/src/functions.php:16
Stack trace:
#0 /root/carddav2fb_XR/src/RunCommand.php(38): Andig\backendProvider('https://www.lio...')
#1 /root/carddav2fb_XR/vendor/symfony/console/Command/Command.php(252): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /root/carddav2fb_XR/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /root/carddav2fb_XR/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /root/carddav2f in /root/carddav2fb_XR/src/functions.php on line 16

url, user und password sind beim server Abschnitt der config.php definiert.
Da meine Programmierkenntnisse sich in Grenzen halten kann ich den Fehler leider nicht lokalisieren. Komme also hier nicht weiter.  Glaube aber nicht dass das hier an PHP7.1 liegt
Es scheint so, dass er den "user" nicht richtig lesen kann. Der "user" hat bei mir einen Punkt im Namen, weiß nicht, ob das unterstützt wird.

Gruß
Axel

**Comment by axelrathey** [comment]
Hallo,
Problem wurde gefunden. in der config.example.php wurden die Änderungen für die Nutzung mehrerer Server nicht nachgeführt. Damit fehlen jetzt je eine öffnende und eine schließende eckige Klammer [ ] wie folgt:

bisher in config.example.php:

    'server' => [
        'url' => '',
        'user' => '',
        'password' => '',
    ],

bitte ändern in 

   'server' => [
        [
            'url' => 'https://...',
            'user' => '',
            'password' => '',
            ],
//								/* add as many as you need
//        [
//           'url' => 'https://...',
//            'user' => '',
//            'password' => '',
//            ],								*/
    ],

Dann startet das script und fängt an die Datensätze vom carddav-Server einzulesen.
Leider hängt es dann bei mir plötzlich nach einigen Datensätzen, wobei ich nicht weiß warum:

Client error: `GET https://......../Axels_Kontakte/C76EC751-2C40-0001-9470-1B0DBDA413D7.vcf` resulted in a `404 Not Found` response:

Scheint gleicher Fehler wie mit dem alten carddav2fb script zu sein. Liegt dann wohl an meinem PHP Konfiguration oder der Quelle Nextcloud Server.

Gruß Axel

**Comment by BlackSenator** [comment]
Hallo Axel,
sorry für verspätetet Rückmeldung. Habe das gerade erst gefunden. Ich arbeite mich jetzt mal durch deine Fehlermeldungen, um die Hinweise einzubauen. Danke erst einmal dafür.

**Comment by BlackSenator** [comment]
Installationsanweisung für Pfadanpassung angepasst
config.example.php angepasst

Der von dir gemeldete Client Error liegt m.E. an deinem CardDAV-Server bzw. an dem ersten korrupten Eintrag in der DB - sonst würde der nicht beginnen die ersten Kontakte einzulesen und dann abbrechen.

Lade dir bitte einmal die aktuelle Version herunter: in dem carddav2fb(_XR)-Verzeichnis:
"git pull https://github.com/BlackSenator/carddav2fb_XR"

Um herauszufinden welcher Datensatz/-sätze schief stehen könntest Du folgendes probieren:
1. in der Datei /src/Backend.php
    ab der Zeile 107 ff. **folgendes** ergänzen*:
   if (in_array($response->getStatusCode(), [200,207])) {
            $body = (string)$response->getBody();
			**Echo $body;**
            return $this->simplify($body, $include_vcards);
        }

2. beim run Befehl ein ** >body.xml** anhängen (schreibt das, was Echo auswirft in die Datei body.xml
    also php carddav2fb.php run >body.xml

Damit das problemlos klappt solltest Du - wenn du das nicht sowieso schon hast: WinSCP und einen guten Editor (z.b. Notepad++) installieren. Damit navigiert es sich leichter als mit der Konsole und manipulationen an den genannten Files sollten auch wie in Win bekannt möglich sein und auf den Raspberry(?) rückgeschrieben werden. Last but not least empfehle ich das notepad++ Plugin XML-Tools - damit lässt sich der Output von body.xml schnell lesbar strukturieren und dann müsstest Du mal die Header-Daten der Kontakte durchsehen, ob Dir was auffällt (z.B. doppeltes vcf: *.vcf.vcf) - letzteres habe ich irgendwo schon mal als Fehlerursache gelesen 

3. Anschl

**Comment by axelrathey** [comment]
Hallo BlackSenator,
danke für Deine Hilfe, werde ich probieren.
WINSCP und Notepad++ nutze ich bereits. Habe ich in winscp gerade mal als Editor eingebunden.
XML Tools nun auch installiert. probiere nachher mal, ob ich den Fehler finde.
Gruß Axel

**Comment by axelrathey** [comment]
Hallo BlackSenator,
ecomme leider eine Fehlermeldung in Verbindung mit "SoapClient" in SOApi.php
Ich vermut mir fehlen einige Einträge in der config.php, weiß aber nicht welche
Hier der volle Fehlertext:

_PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /root/carddav2fb_XR/src/FritzBox/SOApi.php:25
Stack trace:
#0 /root/carddav2fb_XR/src/FritzBox/SOApi.php(43): Andig\FritzBox\SOApi->getSOAPclient()
#1 /root/carddav2fb_XR/src/functions.php(240): Andig\FritzBox\SOApi->getFBphonebook(1)
#2 /root/carddav2fb_XR/src/RunCommand.php(35): Andig\downloadPhonebook(Array)
#3 /root/carddav2fb_XR/vendor/symfony/console/Command/Command.php(252): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /root/carddav2fb_XR/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /root/carddav2fb_XR/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output in /root/carddav2fb_XR/src/FritzBox/SOApi.php on line 25_

Dann erfolgt der Abbruch.
Die SOApi.php ist neu, seit der letzten von mir genutzten Version.

Gruß
Axel

**Comment by BlackSenator** [comment]
Also,

Mit der config.php sollte das nur mittelbar zusammenhängen...
Der SOAP-Client braucht url (IP), user und password der fb aus der 
config.php.
Beim mir läuft das mit
192.168.178.1 oder fritz.box
URL-Angaben mit HTTP://.. oder HTTPS habe ich in der function (bisher) 
nicht abgefangen (kann ich aber mal schauen, was es an fertigen Routinen 
gibt um „clean IP“ zu bekommen.

Ansonsten ist die config.php in dem Segment phonebook ein wenig erweitert:
$config = [
     'phonebook' => [
         'id'           => 0,
         'name'         => 'Telefonbuch',
         'forcedupload' => 2,                   // 3 = CardDAV contacts 
overwrite phonebook on Fritz!Box
     ],                                         // 2 = like 3, but newer 
entries will send as VCF via eMail (-> reply)
                                                // 1 = like 2, but 
vCards are only downloaded if they are newer than the phonebook

wobei das eigentlich mit der fehlerhaften Instantierung nichts zu tun 
haben sollte - schaue ich mir aber mal an...

Wenn das erste nicht schon in die richtige Richtung geht, dann:

1. das mit dem Zielordner und git clone hatte ich ja geändert in der 
Installationsanweisung.
Um von gleichen Ausgangsbedingungen auszugehen:
Ich würde vorschlagen
         sudo mv -r carddav2fb_XR carddav2fb (obwohl es eigentlich auch 
vom ordnerpfad unabhängig ist ...)
2. evtl. überflüssig zu fragen: ist php7.1-soap installiert?
3. fällt mir bestimmt noch was ein, wenn nicht der erste Hinweis die Kuh 
vom Eis bringt ...


Am 26.02.2018 um 19:08 schrieb axelrathey <notifications@github.com 
<mailto:notifications@github.com>>:

**Comment by axelrathey** [comment]
Hallo BlackSenator,

php7.1-soap war der richtige Hinweis, nach dessen Installation startete das Script erst mal.

Es bricht dann leider wieder an der gleichen Stelle nach ein paar eingelesenen Kontakten ab.

Die in Zeile 107 der Backend.php eingefügte Zeile Echo **$body;**
druckt bereits ganz zu anfang was aus. Danach werden einige Kontakte gelesen, bis dann die Sache bei Kontakt 13 abbricht mit:

  Client error: `GET https://<host>/nextcloud/remote.php/da
  v/addressbooks/users/axel.rathey/Axels_Kontakte/C76EC751-2C40-0001-9470-1B0
  DBDA413D7.vcf` resulted in a `404 Not Found` response:
  <?xml version="1.0" encoding="utf-8"?>
  <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:exception>Sabre\DA (truncated...)

Diese Nextcloud liegt auf einem Strato-Server. Ich vermute, dass der die PHP scripte abbricht, wenn das script zu lange dauert. Das carddav2fb läuft bei mir unter raspbian auf einem Bananapi M3. 

Habe den $body jetzt mal durchsucht. Komischerweise werden dort die ersten 12 Kontakt-urls mit .vcf und ab dem 13 Kontakt die url dann mit .vcf.vcf als Endung aufgeführt. 
Bin nun gerade dabei die Kontakte mit .vcf.vcf einzeln aus nextcloud zu exportieren die Datei umzubenennen und dann wieder zu importieren. geht das auch einfacher?

Gruß Axel

**Comment by axelrathey** [comment]
Ok, es läuft jetzt für mein erstes Adressbuch durch, die Kontakte sind nun auf der Fritzbox. Habe in der config.php noch unter 

'phoneReplaceCharacters' => [
            '+49('	=> '0',
            '+49 ('	=> '0',

eingefügt. Die Klammern waren noch aus Outlookzeiten vorhanden und ohne diesen Eintrag war die Vorwahl 0 verschwunden.
Insofern ist die Zeile 
            '+49'   => '',
dort eigentlich falsch und müsste richtig vermutlich
            '+49'   => '0',
sein.

Gruß
Axel

**Comment by BlackSenator** [comment]
Hallo,

das freut mich, das ich mit der Ferndiagnose richtig lag und es jetzt läuft.

Dir Conversions sind nicht bindend, sondern waren nur die, die für meine Daten passend waren/sind - insofern ist es ja richtig, dass Du schauen musst, was für dich passt.

Wie kommentiert, werden die conversions (wenn ich es richtig im Kopf habe) nacheinander durchlaufen, da muss man dann schauen was sinnvolle Reihenfolgen sind...

Wenn noch was ist helfe ich gern
