### ISSUE TITLE
Fotos aus carddav zur Anzeige der Anrufer auf die Fritzbox hochladen und mehrere Zielfritzboxen?

### ISSUE THREAD

**Issue by axelrathey** [BlackSenator/carddav2fb_XR#6]
Hallo BlackSenator,

nachdem das Laden von carddav auf die Fritzbox klappt taucht die Frage auf, ob auch das hochladen der Fotos vom CardDAV Server auf die fritzbox wieder vorgesehen ist. Jedenfalls sind bei mir keine Bilder da.
In den alten Fassungen gab es da wohl eine Option, wobei man aber wohl die Bilder manuell hochladen musste. Habe ich da was übersehen?
Da ich hier 2 Fritzboxen habe, habe ich mir erstmal mit 2 getrennten config.php abgeholfen und diese als Startparameter angegeben. Dabei findet der Einleseprozess natürlich doppelt statt. Es könnte also u.U. sinnvoll sein mehrere Fritzboxen als Ziel zu definieren.

Gruß Axel

**Comment by BlackSenator** [comment]
Hallo Axel,
a) eine Upload-Version für Bilder ist weder in meiner Version, noch in der der von andig (siehe Linke in der Read me) bisher umgesetzt (ehrlich gesagt benötige ich das persönlich nicht und habe z.Z. keine Zeit mich damit tiefer zu befassen - ist auch nicht so hopphopp zu machen (Hintergrund ist, dass es zwei Wege gibt: entweder sind die Bildinformationen direkt in der vCard enthalten oder zur Quelle verlinkt)
b) wenn Du mehrere FritzBoxen hast, dann ist der von dir gewählte Weg über zwei config-Files eigentlich der einfachste. Der Download ist zwar der bottleneck - aber auch bei meinen 1700 Kontakten dauert das nur ein, zwei Minuten... wie oft willst Du den die Synchronisation täglich laufen lassen?
