### ISSUE TITLE
Invalid argument supplied for foreach() in /root/carddav2fb_XR/src/CardDav/Backend.php on line 72

### ISSUE THREAD

**Issue by axelrathey** [BlackSenator/carddav2fb_XR#7]
Hi Blacksenator,
I get an PHP Warning in the backend.php

Invalid argument supplied for foreach() in /root/carddav2fb_XR/src/CardDav/Backend.php on line 72

I'm not sure weather I changed the config file correctly from old to new version. Are there any changes I have to care about?

I get this warning for each carddav-Server.

After reading cards from carddav-Server I get a fatal error like this

Converted and filtered 659 vCard(s)
Detaching and storing image(s)
PHP Fatal error:  Uncaught Error: Call to undefined function Andig\imagecreatefromstring() in /root/carddav2fb_XR/src/functions.php:77
Stack trace:
#0 /root/carddav2fb_XR/src/RunCommand.php(91): Andig\storeImages(Array, '/media/USB-Moun...')
#1 /root/carddav2fb_XR/vendor/symfony/console/Command/Command.php(251): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /root/carddav2fb_XR/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /root/carddav2fb_XR/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /root/carddav2fb_XR/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object( in /root/carddav2fb_XR/src/functions.php on line 77

no fonpix will create neither in cache nor in fritzbox

Do you have an idea where is the problem?

Axel

**Comment by axelrathey** [comment]
Hi Blacksenator,
ok,  I  forget the 

        'substitutes' => [                                          // you must not change this! 
            'PHOTO',                                                // Otherwise image upload failed!
        ],        
 lines. Now I don't get the php warning any more.

Now I get the following error

Downloaded 639 vCard(s)
Downloading vCard(s) from account axel.rathey
    5 [----->----------------------]
In CurlFactory.php line 186:

  cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-er
  rors.html)

I don't know where to search for the CurlFactory.php. Is there a chance to print the wrong url to the console before doing curl?

When I remove this carddav-server from configuration I don't get the CurlFactory error.
To my mind there ist a problem with one of the cards in this carddav-server

Then I get the error of my first mailing like this

Downloaded 638 vCard(s)
Parsing vCards
Converted and filtered 638 vCard(s)
Detaching and storing image(s)
**_PHP Fatal error:  Uncaught Error: Call to undefined function Andig\imagecreatefromstring() in /root/carddav2fb_XR.new/src/functions.php:77
Stack trace:
#0 /root/carddav2fb_XR.new/src/RunCommand.php(91): Andig\storeImages(Array, '/media/USB-Moun...')
#1 /root/carddav2fb_XR.new/vendor/symfony/console/Command/Command.php(251): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /root/carddav2fb_XR.new/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /root/carddav2fb_XR.new/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /root/carddav2fb_XR.new/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Ap in /root/carddav2fb_XR.new/src/functions.php on line 77_**


Thanks for your help 
Axel

**Comment by BlackSenator** [comment]
Sorry for delay - got no email to notify that there is a new issue.

"...changed the config file correctly from old to new version..."
Could you use the programm before without this error?
Do you add a new xerver or just editing contacts?

Am I right, that this error only occure with the '-i' command - right?

**Comment by axelrathey** [comment]
Hi BlackSenator,
now it runs. I think there was a PHP7.1 part was missing I did forget to install.

But there is one problem left. 
When carddav2fb will write dbase-File 
 /media/fritzbox/FRITZ/mediabox/FritzAdr.dbf
it says that this file can't create this file but the carddav2fb script will go on after this error.

This ist the file that I tell carddav2fb in the config_carddav2fb.php file with the following lines

        'fritzadr' => '/media/fritzbox/FRITZ/mediabox/FritzAdr.dbf'    // a mounted storage; if not empty FRITZadr Database
                                                                    // will be written to this location
                                                                    // (will be changed to ftp soon)		

It is also the same, when I put an USB-Stick in the Fritzbox.

Which data will be normaly stored in this dbase file? What ist the purpose of this file?

Thanks Axel

**Comment by axelrathey** [comment]
With one carddav addressbook I get the following error. I don't know why. It is only, when -i is used to transfer the pictures.

In CurlFactory.php line 186:
  cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

For which purposes the CurlFactory.php is used, when workng with the pictures?

Thanks Axel

**Comment by BlackSenator** [comment]
1.
If you don´t use fax4box (Fritz!FAX) you don´t need to set the property  'fritzadr'. If so, the script tries to write a dBase file with fax-numbers of all selected contacts to this dedicated directory.

2.
cURL-libraries are are used to connect with CardDAV-Server. 
CardDAV e.g. vCards cold store Images in to ways:
- directly (binary) as Base64 data
- a link to an other destination on the server, where the data are stored
My image download solution is designed in this way:
During downloading the vCards, if images are linked, the script tries to download the image data from the link and then the link will be substitute with the downloaded base64 data.
As long as the linked directory/url is reachable with the same credentials as the CardDAV server - everything goes fine. If the link is outside the CardDAV server it might be fail.
But I´m sorry for the next few month I haven´t had the time to investigate this. But I will as soon as possible.

Regards

Black Senator

**Comment by axelrathey** [comment]
Hi,

after changing the photo in th above carddav addressbook it works without the cURL error 3.
I supose the old jpg photo was not properly formated. 

Regards
Axel
