### ISSUE TITLE
Missing conversion definition for `realName`

### ISSUE THREAD

**Issue by Seoman7** [BlackSenator/carddav2fb_XR#9]
Hi!
After my Installation the execution of the script exits with the following error:

```
root@cloud:/carddav2fb# php carddav2fb.php run
PHP Warning:  Module 'dbase' already loaded in Unknown on line 0
PHP Warning:  Module 'dbase' already loaded in Unknown on line 0
Downloading vCard(s) from account Andreas Schad
  668 [============================]
Downloaded 668 vCard(s)
Parsing vCards
Converted and filtered 668 vCard(s)
PHP Notice:  Undefined index: conversions in /carddav2fb/src/FritzBox/Converter.php on line 19

In Converter.php line 174:

  Missing conversion definition for `realName`


run [-i|--image] [-c|--config CONFIG]

```
Do you have any hints for me?

here is my config.php:

`<?php

$config = [
    
    'script' => [
        'cache' => '/media/Imation-USBFlashDrive-00/carddav2fb/cache',        // your stick, drive or share designated for caching 
        'log'   => '/media/Imation-USBFlashDrive-00/carddav2fb/cache',        // at you Raspberry, on your NAS or ...
    ], 

    'server' => [
        [
            'url'      => 'XXX',
            'user'     => 'XXX',
            'password' => 'XXX!',
            ],                                                     /* 
        [
            'url'      => 'YYY',
            'user'     => 'XXX',
            'password' => 'XXX',
            ],                                                      */
    ],

    'fritzbox' => [
        'url'      => 'XXX',
        'user'     => 'XXX',                                     // e.g. 'dslf-config' AVM standard user for usual login
        'password' => 'XXX',
        'fonpix'   => '/Imation-USBFlashDrive-00/FRITZ/fonpix',               // the additional usb memory at the Fritz! box
        'fritzadr' => '/media/fritzbox/FRITZ/mediabox/FritzAdr.dbf',    // a mounted storage; if not empty FRITZadr Database
                                                                    // will be written to this location
                                                                    // (will be changed to ftp soon)
    ],

    'phonebook' => [
        'id'           => 0,               // only '0' can store quick dial and vanity numbers as well as images 
        'name'         => 'Telefonbuch',
        'imagepath'    => 'file:///var/InternerSpeicher/Imation-USBFlashDrive-00/FRITZ/fonpix/', // mandatory if you use the -i option
        'forcedupload' => 3,               // 3 = CardDAV contacts overwrite phonebook on Fritz!Box
    ],                                     // 2 = like 3, but newer entries will send as VCF via eMail (-> reply)
                                           // 1 = like 2, but vCards are only downloaded if they are newer than the phonebook

    'reply' => [                                                    // mandatory if you use "forcedupload" < 3 ! 
        'url'      => 'XXX',
        'port'     => 587,                                          // alternativ 465
        'secure'   => 'tls',                                        // alternativ 'ssl'
        'user'     => 'XXX',                                     // your sender email adress e.g. account
        'password' => 'XXX',
        'receiver' => 'XXX',                  // your email adress to receive the secured contacts  
        'debug'    => 0,                                            // 0 = off (for production use)
                                                                    // 1 = client messages
                                                                    // 2 = client and server messages
    ],

    'filters' => [
        'include' => [                                              /* if empty include all by default
            'categories' => [                                          if your server is iCloud, groups can be used (XOR)
            ],
            'group' => [
            ],                                                      */
        ],

        'exclude' => [
            'categories' => [
                'A',
                'B',
                'C',
            ],                                                      /*
            'group' => [                                               if your server is iCloud, groups can be used (XOR)
                'D',
                'E',
                'F',
            ],                                                      */
        ],

    'conversions' => [
        
        'substitutes' => [                                          // you must not change this! 
            'PHOTO',                                                // Otherwise image upload failed!
        ],        
        
        'vip' => [
            'categories' => ['VIP'                                  // the category / categories, which should be marked as VIP
            ],
        
		],
        
        'realName' => [                                             // are processed consecutively. Order decides!
            '{lastname}, {firstname}',
            '{lastname}, {prefix} {nickname}',
            '{lastname}, {prefix} {firstname}',
            '{lastname}, {nickname}',
            '{organization}',
            '{fullname}',
        ],

        'phoneTypes' => [                                           // you mustn´t define 'fax'!
            'WORK'    => 'work',                                    // this conversion is set fix in code!
            'HOME'    => 'home',
            'CELL'    => 'mobile',
            'MAIN'    => 'work',
            'FAX'     => 'fax',
            'default' => 'home',
        ],

        'emailTypes' => [
            'WORK' => 'work',
            'HOME' => 'home',
        ],
        
        'phoneReplaceCharacters' => [                               // are processed consecutively. Order decides!
            '+491'  => '01',                                        // domestic numbers without country code
            '+492'  => '02',
            '+493'  => '03',
            '+494'  => '04',
            '+495'  => '05',
            '+496'  => '06',
            '+497'  => '07',
            '+498'  => '08',
            '+499'  => '09',
            '+49 1' => '01',
            '+49 2' => '02',
            '+49 3' => '03',
            '+49 4' => '04',
            '+49 5' => '05',
            '+49 6' => '06',
            '+49 7' => '07',
            '+49 8' => '08',
            '+49 9' => '09',
            '+49'   => '',
            '('     => '',                                          // delete separators
            ')'     => '',
            '/'     => '',
            '-'     => '',
            '+'     => '00',                                         // normalize foreign numbers
        ]
    ]
]
];
`
For it looks nice. Perhaps you've got some fints for me?
best regards 
Andreas

**Comment by caldir65** [comment]
Hi,

I've the same problem ...
`<?php

$config = [
   
    'script' => [
        'cache' => './carddav2fb/cache',        // your stick, drive or share designated for caching
        'log'   => './carddav2fb/cache',        // at you Raspberry, on your NAS or ...
    ],

    'server' => [
        [
        'url'      => 'https://xxxxxxxxxxxxxxxx/remote.php/dav/addressbooks/users/christoph/familie/',
        'user'     => 'christoph',
        'password' => 'xxxxxxxx',
        ]
    ],

    'fritzbox' => [
        'url'      => 'fritz.box',
        'user'     => 'xxxxxxxx',                                     // e.g. 'dslf-config' AVM standard user for usual login
        'password' => 'xxxxxxxx',
        'fonpix'   => '/WDC WD10 EARS-00Y5B1/FRITZ/fonpix',               // the additional usb memory at the Fritz! box
        'fritzadr' => '/media/fritzbox/FRITZ/mediabox/FritzAdr.dbf'    // a mounted storage; if not empty FRITZadr Database
                                                                       // will be written to this location
                                                                       // (will be changed to ftp soon)
    ],

    'phonebook' => [
        'id'           => 0,               // only '0' can store quick dial and vanity numbers as well as images
        'name'         => 'Telefonbuch_Test',
        'imagepath'    => 'file:///var/InternerSpeicher/WDC WD10 EARS-00Y5B1/FRITZ/fonpix/', // mandatory if you use the -i option
        'forcedupload' => 3,               // 3 = CardDAV contacts overwrite phonebook on Fritz!Box
    ],                                     // 2 = like 3, but newer entries will send as VCF via eMail (-> reply)
                                           // 1 = like 2, but vCards are only downloaded if they are newer than the phonebook

    'reply' => [                                                    // mandatory if you use "forcedupload" < 3 !
        'url'      => 'smtp...',
        'port'     => 587,                                          // alternativ 465
        'secure'   => 'tls',                                        // alternativ 'ssl'
        'user'     => '[USER]',                                     // your sender email adress e.g. account
        'password' => '[PASSWORD]',
        'receiver' => 'cool.chris65@web.de',                  // your email adress to receive the secured contacts
        'debug'    => 0,                                            // 0 = off (for production use)
                                                                    // 1 = client messages
                                                                    // 2 = client and server messages
    ],

    'filters' => [
        'include' => [                                              /* if empty include all by default
            'categories' => [                                          if your server is iCloud, groups can be used (XOR)
            ],
            'group' => [
            ],                                                      */
        ],

        'exclude' => [
            'categories' => [
                'A',
                'B',
                'C',
            ],                                                      /*
            'group' => [                                               if your server is iCloud, groups can be used (XOR)
                'D',
                'E',
                'F',
            ],                                                      */
        ],

    'conversions' => [
       
        'substitutes' => [                                          // you must not change this!
            'PHOTO',                                                // Otherwise image upload failed!
        ],      
       
        'vip' => [
            'categories' => ['VIP'                                  // the category / categories, which should be marked as VIP
            ],
        ],
       
        'realName' => [                                             // are processed consecutively. Order decides!
            '{lastname}, {prefix} {nickname}',
            '{lastname}, {prefix} {firstname}',
            '{lastname}, {nickname}',
            '{lastname}, {firstname}',
            '{organization}',
            '{fullname}'
        ],

        'phoneTypes' => [                                           // you mustn´t define 'fax'!
            'WORK'    => 'work',                                    // this conversion is set fix in code!
            'HOME'    => 'home',
            'CELL'    => 'mobile',
            'MAIN'    => 'work',
            'FAX'     => 'fax',
            'default' => 'home',
        ],

        'emailTypes' => [
            'WORK' => 'work',
            'HOME' => 'home'
        ],
       
        'phoneReplaceCharacters' => [                               // are processed consecutively. Order decides!
            '+491'  => '01',                                        // domestic numbers without country code
            '+492'  => '02',
            '+493'  => '03',
            '+494'  => '04',
            '+495'  => '05',
            '+496'  => '06',
            '+497'  => '07',
            '+498'  => '08',
            '+499'  => '09',
            '+49 1' => '01',
            '+49 2' => '02',
            '+49 3' => '03',
            '+49 4' => '04',
            '+49 5' => '05',
            '+49 6' => '06',
            '+49 7' => '07',
            '+49 8' => '08',
            '+49 9' => '09',
            '+49'   => '',
            '('     => '',                                          // delete separators
            ')'     => '',
            '/'     => '',
            '-'     => '',
            '+'     => '00'                                         // normalize foreign numbers
        ]
    ]
 ]
];`

Is there a solution?

Greetz, Christoph

**Comment by BlackSenator** [comment]
Sorry for delay,
I still haven´t managed to configure GitHub sending me an email if an issue is reported.

Now to your reported bug:
As correctly guessed the reason must be somewhere in the **config.php**. But I cant see even any mistake why the definition for `realName` is not propperly loaded.

Please refer to the
**/scr/RunCommand.php** in the
`protected function execute`
and below
`$this->loadConfig ($input);`
insert the debugging line
`print_r ($this->config);`
This will write the array contents of the config data to the screen.
Save your changings!
Run the script.
When the vCard download starts, press CTRL-C to cancel the run.
Now you can browse through the output array in the console. I hope you can see better where to find a hint why this error appears.

**Comment by Seoman7** [comment]
Here you'll find the output, but that doesn't help me much. Perhaps there is something worng with the pathes for the adressbook?:

`
Array
(
    [script] => Array
        (
            [cache] => /media/cloud/carddav2fb/cache
            [log] => /media/cloud/carddav2fb/cache
        )

    [server] => Array
        (
            [0] => Array
                (
                    [url] => https://XXX/remote.php/dav/addressbooks/users/1ABB7349-F6C8-4A75-BFEB-D88AA76D401A/Andreas/
                    [user] => XXX
                    [password] => XXX
                )

        )

    [fritzbox] => Array
        (
            [url] => XXX
            [user] => admin
            [password] => XXX
            [fonpix] => /Imation-USBFlashDrive-00/FRITZ/fonpix
            [fritzadr] => /media/fritzbox/FRITZ/mediabox/FritzAdr.dbf
        )

    [phonebook] => Array
        (
            [id] => 0
            [name] => Telefonbuch
            [imagepath] => file:///var/InternerSpeicher/Imation-USBFlashDrive-00/FRITZ/fonpix/
            [forcedupload] => 3
        )

    [reply] => Array
        (
            [url] => XXX
            [port] => 587
            [secure] => tls
            [user] => XXX
            [password] => XXX
            [receiver] => XXX
            [debug] => 0
        )

    [filters] => Array
        (
            [include] => Array
                (
                )

            [exclude] => Array
                (
                    [categories] => Array
                        (
                            [0] => A
                            [1] => B
                            [2] => C
                        )

                )

            [conversions] => Array
                (
                    [substitutes] => Array
                        (
                            [0] => PHOTO
                        )

                    [vip] => Array
                        (
                            [categories] => Array
                                (
                                    [0] => VIP
                                )

                        )

                    [realName] => Array
                        (
                            [0] => {lastname}, {firstname}
                            [1] => {organization}
                            [2] => {fullname}
                        )

                    [phoneTypes] => Array
                        (
                            [WORK] => work
                            [HOME] => home
                            [CELL] => mobile
                            [MAIN] => work
                            [FAX] => fax
                            [default] => home
                        )

                    [emailTypes] => Array
                        (
                            [WORK] => work
                            [HOME] => home
                        )

                    [phoneReplaceCharacters] => Array
                        (
                            [+491] => 01
                            [+492] => 02
                            [+493] => 03
                            [+494] => 04
                            [+495] => 05
                            [+496] => 06
                            [+497] => 07
                            [+498] => 08
                            [+499] => 09
                            [+49 1] => 01
                            [+49 2] => 02
                            [+49 3] => 03
                            [+49 4] => 04
                            [+49 5] => 05
                            [+49 6] => 06
                            [+49 7] => 07
                            [+49 8] => 08
                            [+49 9] => 09
                            [+49] => 
                            [(] => 
                            [)] => 
                            [/] => 
                            [-] => 
                            [+] => 00
                        )

                )

        )

)
Downloading vCard(s) from account Andreas Schad
  492 [============================]
Downloaded 492 vCard(s)
Parsing vCards
Converted and filtered 492 vCard(s)
PHP Notice:  Undefined index: conversions in /carddav2fb/src/FritzBox/Converter.php on line 19

In Converter.php line 174:
                                                
  Missing conversion definition for `realName`  
                                                

run [-i|--image] [-c|--config CONFIG]

`

Somebody any hints for me ?
best regards 
Andreas

**Comment by caldir65** [comment]
Hi,

maybe there is a problem in the RunCommand.php? This is very different from Andigs original... ?

Greetz

**Comment by BlackSenator** [comment]
Solution moved to https://github.com/BlackSenator/carddav2fb
